src/Entity/Message.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MessageRepository")
 */
class Message
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $published_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ip;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->published_at;
    }

    public function setPublishedAt(?\DateTimeInterface $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    public function getIp(): ?string
    {
        return $this->ip;
    }

    public function setIp(?string $ip): self
    {
        $this->ip = $ip;

        return $this;
    }
}

src/Entity/User.php
<?php
// src/Entity/User.php

namespace App\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    public function __construct()
    {
        parent::__construct();
        // your own logic
    }

}

src/Form/MessageType.php
<?php

namespace App\Form;

use App\Entity\Message;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('lastname')
            ->add('firstname')
            ->add('email')
            ->add('text')
            ->add('published_at', DateType::class, [
               /* permet de faire apparaître un datepicker */
                'widget' => 'single_text',
               /* permet de régler automatiquement la date à la date du jour */
                'data' => new \DateTime("now")
            ])
            ->add('ip')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Message::class,
        ]);
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')
            ->add('usernameCanonical')
            ->add('email')
            ->add('emailCanonical')
            ->add('enabled')
            ->add('password')
            ->add('lastLogin')
            ->add('passwordRequestedAt')
            ->add('roles');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Form\MessageType;
use App\Repository\MessageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     *
     */
    public function home(MessageRepository $messageRepository)
    {
        $messages = $messageRepository->findAll();
        return $this->render('homepage.html.twig', [
            'messages' => $messages
        ]);
    }

    /**
     * @Route("/admin", name="admin")
     * Méthode pour rediriger sur la page de connexion via le chemin /admin si l'admin n'est pas connecté
     */
    public function admin()
    {
        if ($this->isGranted('ROLE_ADMIN')) {
            return $this->redirectToRoute('home');
        } else {
            return $this->redirectToRoute('fos_user_security_login');
        }
    }

    /**
     * @Route("/contact", name="contact")
     */
    public function contact(EntityManagerInterface $entityManager, Request $request, ValidatorInterface $validator)
    {
        $message = new Message();
        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            // On envoie le message en base de données grâce aux méthodes persist(objet) + flush
            // persist + flush est l'équivalent de commit + push de Git.
            $entityManager->persist($message);
            $entityManager->flush();
            $this->addFlash('Success', 'Salut '. $message->getFirstname() . '! Votre message a bien été envoyé.');
        }
        //si le formulaire est soumis (submit)
            //utilisation de la fonctoin mail()
        return $this->render('contact.html.twig', [
            'messageForm' => $form->createView(),
            'message' => $message
        ]);
    }


    /**
     * @Route("/admin/messages", name="messages")
     */
     public function messages(MessageRepository $messageRepository)
     {
         $messages = $messageRepository->findAll();
         return $this->render('messages.html.twig', [
             'messages' => $messages
         ]);
     }


}

templates/base/_header.html.twig
<header>

    <div class="bs-example">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <a href="{{ path('home') }}" class="navbar-brand">
                <div class="col-md-3">
                    <img class="logo" src="{{ asset('assets/img/logo.png') }}" alt="" />
                </div>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav menu-top">
                    <a href="{{ path('home') }}" class="nav-item nav-link">Accueil</a>
                    <a href="{{ path('contact') }}" class="nav-item nav-link">Contact</a>
                    <a class="nav-link nav-item" href="{{ path('fos_user_security_login') }}">Login/admin</a>
                </div>

            </div>
        </nav>
        <span class="header-title-bottom">
              {# si un utilisateur est connecté en tant qu'admin #}
            {% if is_granted('ROLE_ADMIN') %}
            <div class="bouton">
                <a href="{{ path('fos_user_security_logout') }}">Se déconnecter</a>
            </div>
            {% endif %}
        </span>

    </div>

</header>

templates/base/base.html.twig
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}

    <title>Club de Yoga</title>

    {% endblock %}
    {#pour menu burger#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
    {#pour afficher favicon#}
    <link rel="icon" type="image/png" href="{{ asset('assets/img/logo.png') }}">
    {#jquery for carousel#}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {#pour animer le texte#}
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>

<body>

    {% include 'base/_header.html.twig' %}

    <div class="flash-messages">
        {% for messages in app.flashes %}
        <div class="flash-message">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </div>
        {% endfor %}
    </div>

    {% block main %}

    {% endblock %}

</body>

</html>

templates/bundles/FOSUserBundle/Profile/edit_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}

{{ form_start(form, { 'action': path('fos_user_profile_edit'), 'attr': { 'class': 'fos_user_profile_edit' } }) }}
    {{ form_widget(form) }}
    <div>
        <input type="submit" value="{{ 'profile.edit.submit'|trans }}" />
    </div>
{{ form_end(form) }}

templates/bundles/FOSUserBundle/Profile/show_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}

<div class="fos_user_user_show">
    <p>{{ 'profile.show.username'|trans }}: {{ user.username }}</p>
    <p>{{ 'profile.show.email'|trans }}: {{ user.email }}</p>
    <a href="{{ path('home') }}" class="redirect-home">Revenir à l'accueil</a>
</div>

templates/bundles/FOSUserBundle/Resetting/email.txt.twig
{% trans_default_domain 'FOSUserBundle' %}
{% block subject %}
{%- autoescape false -%}
{{ 'resetting.email.subject'|trans({'%username%': user.username}) }}
{%- endautoescape -%}
{% endblock %}

{% block body_text %}
{% autoescape false %}

    Bonjour {{ user.username }} !

    Pour réinitialiser votre mot de passe, merci de vous rendre sur {{ confirmationUrl }}

    Bonne journée,

    l'équipe technique.
{#{{ 'resetting.email.message'|trans({'%username%': user.username, '%confirmationUrl%': confirmationUrl}) }}#}
{% endautoescape %}
{% endblock %}
{% block body_html %}{% endblock %}

templates/bundles/FOSUserBundle/Security/login_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}

{% if error %}
    <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
{% endif %}

<form action="{{ path("fos_user_security_check") }}" method="post">
    {% if csrf_token %}
        <input type="hidden" name="_csrf_token" value="{{ csrf_token }}" />
    {% endif %}

    <input type="text" placeholder="Adresse email" id="username" name="_username" value="{{ last_username }}" required="required" autocomplete="username" />

    <input type="password" placeholder="Mot de passe" id="password" name="_password" required="required" autocomplete="current-password" />

    <input type="submit" id="_submit" name="_submit" value="{{ 'security.login.submit'|trans }}" />

    {% if not is_granted("IS_AUTHENTICATED_REMEMBERED") %}
        <a class="forgotten-password" href="{{ path('fos_user_resetting_request') }}">Mot de passe oublié ?</a>
    {% endif %}
</form>

templates/bundles/FOSUserBundle/layout.html.twig
{% extends 'base/base.html.twig' %}

{% block title %}

    <title>Se connecter</title>

{% endblock %}

{% block main %}

    <div class="container-login ">
        {% if app.request.attributes.get('_route') == 'fos_user_security_login' %}
            <h1 class="log-title">Se connecter</h1>
        {% elseif app.request.attributes.get('_route') == 'fos_user_resetting_request' %}
            <h1 class="log-title">Réinitialiser le mot de passe</h1>
        {% elseif app.request.attributes.get('_route') == 'fos_user_resetting_check_email' %}
            <h1 class="log-title">Email envoyé</h1>
        {% elseif app.request.attributes.get('_route') == 'fos_user_change_password' %}
            <h1 class="log-title">Modifier le mot de passe</h1>
        {% endif %}
        <div class="block-login">

            {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
                <div class="connected-user">
                    {{ 'layout.logged_in_as'|trans({'%username%': app.user.username}, 'FOSUserBundle') }} |
                    <a href="{{ path('fos_user_security_logout') }}">
                        {{ 'layout.logout'|trans({}, 'FOSUserBundle') }}
                    </a>
                </div>
            {% endif %}

            {% if app.request.hasPreviousSession %}
                {% for type, messages in app.session.flashbag.all() %}
                    {% for message in messages %}
                        <div class="flash-{{ type }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endfor %}
            {% endif %}

            <div>
                {% block fos_user_content %}
                {% endblock fos_user_content %}
            </div>
        </div>
    </div>

{% endblock %}

templates/contact.html.twig
{% extends 'base/base.html.twig' %}

{% block main %}

    <h2 class="join">Contact</h2>

    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <div class="map">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2832.094404434966!2d-0.5887748496327432!3d44.7788806868279!2m3!1f0!2f0!3f0!
                    3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd55274c294efbdb%3A0x5ddaf92b7fe54284!2sLa+Tannerie!5e0!3m2!1sfr!2sfr!4v1566120239726!5m2!1sfr!2sfr"
                            width="100%" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
                </div>
            </div>
            <div class="col-md-5">
                <p class="m_1">L’association « Yoga Gradignan » est responsable des traitements opérés sur le site accessible à l’adresse https://www.yoga-club.com.
                    Les informations recueillies font l’objet d’un traitement informatique à des fins de suivi de votre demande de contact. Les destinataires
                    des données sont les membres du bureau de l'association, et/ou le cas échéant les salariés ou les bénévoles de l’association en charge de cette mission.
                    Vos données à caractère personnel sont conservées dans nos bases le temps nécessaire au traitement de votre demande.</p>
                <div class="address">
                    <p>Club Yoga, Parc La Tannerie</p>
                    <p>33170, Gradignan,</p>
                    <p>France</p>
                    <p>Téléphone: 06 00 22 66 44</p>
                    <p>Fax: 05 00 00 00 00</p>
                    <p>Email: <span>support[at]yoga.com</span></p>
                </div>
            </div>
        </div>

        {# Balise ouvrante <form> #}

        {{ form_start(messageForm, {'attr': {'class': 'form'}}) }}

        {# balise <label> #}
        {{ form_label(messageForm.lastname, 'Nom', {'label_attr': {'class': 'form-label'}}) }}
        {# balise input #}
        {{ form_widget(messageForm.lastname, {'attr': {'class': 'form-input'}}) }}

        {{ form_label(messageForm.firstname, 'Prénom', {'label_attr': {'class': 'form-label'}}) }}
        {{ form_widget(messageForm.firstname, {'attr': {'class': 'form-input'}}) }}

        {{ form_label(messageForm.email, 'Email', {'label_attr': {'class': 'form-label'}}) }}
        {{ form_widget(messageForm.email, {'attr': {'class': 'form-input form-input'}}) }}

        {{ form_label(messageForm.published_at, 'Date', {'label_attr': {'class': 'form-label'}}) }}
        {{ form_widget(messageForm.published_at, {'attr': {'class': 'form-input'}}) }}

        {{ form_label(messageForm.text, 'Message', {'label_attr': {'class': 'form-label'}}) }}
        {{ form_widget(messageForm.text, {'attr': {'class': 'form-input'}}) }}

        <button class="form-submit" type="submit">Envoyer</button>

        {# Balise fermante </form> #}
        {{ form_end(messageForm) }}

    </div>

{% endblock %}

templates/homepage.html.twig
{% extends 'base/base.html.twig' %}

{% block main %}
    <div class="bouton">
        {# si un utilisateur est connecté en tant qu'admin #}
        {% if is_granted('ROLE_ADMIN') %}
            <a href="{{ path('messages') }}" class="organisateur-update" title="Afficher des messages">
                Afficher des messages
            </a>
        {% endif %}
    </div>
    <div class="intro">
        <p>Bienvenue au club de Hatha yoga!</p><br>
        <p>
            Hatha yoga signifie « yoga d'effort » et concerne principalement l'éveil spirituel par les postures correctes (āsana), la discipline du souffle (prāṇāyāma)1 et la méditation (dhyāna). Il constitue une pratique sous des formes diverses s'appuyant sur le travail corporel et l'attitude mentale correspondante et fait aussi l'objet d'un commerce dans le monde du développement personnel et du marché du bien-être.
        </p><br>
        <p> N'hésitez pas à nous appeler au : 06 00 00 00 00</p>
    </div>
    <h2 class="join">Gallerie</h2>
     <article id="carouselExampleControls" class="carousel slide slide-card" data-ride="carousel">
         <div class="carousel-inner slide-infos">
            <div class="carousel-item active slide-image bg-img" style="background-image: url('{{ asset('assets/img/2018_Yoga.jpg') }}')">
            </div>
            <div class="carousel-item slide-image bg-img" style="background-image: url('{{ asset('assets/img/yoga.jpg') }}')">
            </div>
            <div class="carousel-item slide-image bg-img" style="background-image: url('{{ asset('assets/img/yoga-in-the-park.jpg') }}')">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
     </article>

{% endblock %}

templates/messages.html.twig
{% extends 'base/base.html.twig' %}

{% block main %}
    <div class="all-messages">
        {% for message in messages %}

            <div class="date">
                <p>Reçu le: {{ message.publishedAt|date('d m Y') }}</p>
                <h2 class="name">{{ message.firstname }} {{ message.lastname }} {{ message.email }} </h2>
                <p>{{ message.ip }}</p>
                <div class="message">{{ message.text }}</div>
            </div>

        {% endfor %}
    </div>
{% endblock %}